name = "HorizonSideRobots"
uuid = "d5e94110-5307-4c9c-bf91-3c01b52f9d89"
authors = ["Виктор Федоров <fdorov@mail.ru>"]
version = "0.3.1"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "1"
PyPlot = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
